config/routes.rb
Rails.application.routes.draw do
  api_version(:module => "V1", :path => {:value => "/api/v1"}) do
    resources :data, :only => [:index, :show, :create, :update, :destroy]
  end

  get 'users/show', :as => '/user'
  post 'api_key/create' => 'users#create_api_key'
  post 'api_key/:key/delete' => 'users#delete_api_key'

  root 'data#index'

  resources :data

  get 'tags/:tags/:function' => 'tags#show'
  get 'tags/:tags' => 'tags#show'

  get '/auth/google_oauth2', :as => 'signin'
  match 'auth/:provider/callback' => 'sessions#create', :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', :as => 'signout', :via => [:get, :post]
end

app/views/layouts/_topnav.html.erb
<div class="auth">
  <% if current_user %>
    <%= link_to current_user.email, user_path %> |
    <%= link_to "Sign out", signout_path %>
  <% else %>
    <%= link_to "Sign in with Google", signin_path %>
  <% end %>
</div>

<nav class="top-bar" role="navigation">
  <div class="row title-area">
    <div class="name small-1 medium-3 large-2 columns">
      <h1><a href="<%=root_url%>">Tagged Data</a></h1>
    </div>

    <div class="search-area small-11 medium-9 large-10 columns">
      <div class="row collapse">
        <div class="small-9 columns">
          <input id="search-text" type="text" placeholder="Search via tags (eg: #sfo #weather)"
            <% if @tags && @tags.count > 0 %>
              value="<%= @tags.map {|t| "##{t}"}.join(" ") + " " %>"
            <% end %>
          >
        </div>

        <div class="small-3 columns">
          <a href="#" id="search-button" class="alert button expand">Search</a>
        </div>
      </div>
    </div>
  </div>
</nav>

<script>
  function doSearch() {
    var text = $('#search-text').val().trim().replace(/#+/g, "").replace(/[\s,]+/g, ",");
    var functionSuffix = "/<%= @function || '' %>";
    if (text.length > 0) {
      window.location.href = "/tags/" + text + functionSuffix;
    } else {
      window.location.href = "/";
    }
  };

  $(function() {
    $('#search-button').click(function(event) { doSearch(); });
    $('#search-text').keyup(function(event) {
      if(event.which == 13) { doSearch(); }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Tagged Data | data.asif.in" %></title>

    <%= stylesheet_link_tag    "application" %>

    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if content_for?(:header) %>
      <%= yield :header %>
    <% else %>
      <%= render :partial => 'layouts/topnav' %>
    <% end %>

    <div class="container row">
      <%= yield %>
    </div>
  </body>
</html>